services:
  wordpress:
    depends_on:
      - database
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: "${MYSQL_HOST}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - ./wp-content:/var/www/html/wp-content

  database:
    image: mysql:9.3.0
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
